development:
  host: thevideofeed.local
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  admin_password: test
  hoptoad_key: a18fe0a2cd5f68f3a64de0c6ea20eb8f

test:
  host: thevideofeed.test
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  admin_password: test

production:
  host: thevideofeed.com
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  google_analytics: UA-2350501-12
  admin_password: 92dce5db985
  hoptoad_key: a18fe0a2cd5f68f3a64de0c6ea20eb8f
