development:
  host: thevideofeed.local
  mailer: noreply@thevideofeed.com
  name: thevideofeed

test:
  host: thevideofeed.test
  mailer: noreply@thevideofeed.com
  name: thevideofeed

production:
  host: thevideofeed.com
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  google_analytics: UA-2350501-12