development:
  host: thevideofeed.local
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  admin_password: test
  hoptoad_key: f4fee383c087c4eaea1f228ab066c38c

test:
  host: thevideofeed.test
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  admin_password: test

production:
  host: thevideofeed.com
  mailer: noreply@thevideofeed.com
  name: thevideofeed
  google_analytics: UA-2350501-12
  admin_password: 92dce5db985
  hoptoad_key: f4fee383c087c4eaea1f228ab066c38c
