development:
# sqlite3
  # adapter: sqlite3
  # database: db/development.sqlite3
  # timeout: 5000
# postgresql
  adapter: postgresql
  database: thevideofeed_development
  username: trevorturk
  password: 
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
